### ISSUE TITLE
릴리즈 된 binary 실행 시  template을 찾을 수 없다고 나옵니다.

### ISSUE THREAD

**Issue by theplan9** [haje01/loglab#1]
binary로 html이나 cs 코드를 생성하려고 할때 
Traceback (most recent call last):
  File "loglab\cli.py", line 133, in <module>
  File "click\core.py", line 1128, in __call__
  File "click\core.py", line 1053, in main
  File "click\core.py", line 1659, in invoke
  File "click\core.py", line 1395, in invoke
  File "click\core.py", line 754, in invoke
  File "loglab\cli.py", line 129, in object
  File "loglab\doc.py", line 376, in object_from_labfile
  File "jinja2\environment.py", line 997, in get_template
  File "jinja2\environment.py", line 958, in _load_template
  File "jinja2\loaders.py", line 125, in load
  File "jinja2\loaders.py", line 214, in get_source
jinja2.exceptions.TemplateNotFound: tmpl_obj.cs.jinja
[28028] Failed to execute script 'cli' due to unhandled exception!
에러가 발생합니다.

template를 추가하면 될 것 같은데 경로가 어떻게 되는지 확인 가능할까요?

**Comment by haje01** [comment]
바이너리 빌드시 템플릿 파일 지정이 빠졌습니다. 
수정 후 Release 에 v0.1.5로 다시 올렸습니다. 
다시 받아보시면 될 듯합니다.
